# Generated by Django 4.2.7 on 2025-11-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Aprovação'),
        ),
        migrations.AddField(
            model_name='article',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status de Aprovação'),
        ),
        migrations.AddField(
            model_name='article',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='article',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
    ]
